### ISSUE TITLE
roleName too long

### ISSUE THREAD

**Issue by tgensol** [thundra-io/serverless-plugin-thundra-monitor-cw#1]
Hi guys,

When I want to use this plugin, I am getting : 

```
Serverless Error ---------------------------------------

  An error occurred: ThundraDashmonitorDashcwDashserverlessDashneo4jDashpythonuseast1Role - 1 validation error detected: Value 'ThundraDashmonitorDashcwDashserverlessDashneo4jDashpythonuseast1Role' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.
```

How can I do ?

It is possible (or could be) to set the roleName like this : 

```
thundraMonitorFunctionMemorySize: 1536
thundraMonitorRoleName: myRoleName
```

Best !

**Comment by serkan-ozal** [comment]
Hi @tgensol,

Thanks for reporting the issue.

Unfortunately setting role name is not configurable at the moment. But as you suggested, giving it through configuration is a good way for handling such cases :+1:

I will add this configuration support and publish a new version as soon as possible.

Thanks.

**Comment by serkan-ozal** [comment]
Hi @tgensol,

I have introduced optional `thundraMonitorFunctionName` and `thundraMonitorRoleName` properties to configure Thundra monitoring Lambda function name and role name as explained in the doc: https://github.com/thundra-io/serverless-plugin-thundra-monitor-cw/blob/master/README.md#configuration

In your case, you can configure `thundraMonitorRoleName` to a shorter name . However, default generated role name should be enough because there is no `...dash...` replacements for unsupported characters anymore (they are just removed)

**Comment by tgensol** [comment]
Hi @serkan-ozal ,

You guys are working fast ! I did not get the error with the new update, without using thundraMonitorRoleName as expected.

Thanks !
